///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
//#include <stdio.h>
//#include <android/log.h>
///* Header for class com_example_jni_Native */
//#define  LOG_TAG    "HelloJni"
//#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
//#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
//
///*
// * Class:     com_example_jni_Native
// * Method:    add
// * Signature: (II)I
// */
//JNIEXPORT jint JNICALL Java_com_example_jni_Native_add
//  (JNIEnv *env, jclass jclazz, jint a, jint b) {
//
//};
//
//JNIEXPORT jint JNICALL Java_com_example_jni_Native_add__II
//  (JNIEnv *env, jclass jclazz, jint a, jint b){
//	(*env)->NewIntArray(env, 10);
//	jint nativearray[10];
//	// 对副本进行复制,然后set回去的操作复杂
//	unsigned char* buffer = (unsigned char*) malloc(1024);
//	jobject directBuffer;
//	env->NewDirectByteBuffer(env, buffer, 1024);
////	env->GetDirectBufferAddress()
////	env->GetFieldID()
////	env->GetObjectField
//	jthrowable ex;
//	ex = env->ExceptionOccurred(env);
//	if (0 != ex) {
//		// 发生异常
//		(*env)->ExceptionClear(env);
//	}
//	jclass localClazz;
//	jclass globalClazz;
//
//	localClazz = env->FindClass(env, "java/lang/String");
//	globalClazz = (*env)->NewGlobalRef(env, localClazz);
//	// 全局引用只能显示的释放
//	(*env)->DeleteGlobalRef(env, globalClazz);
//	// 弱全局引用在原生方法的后续调用过程中依然有效,与全局引用不同,若全局引用并不组织潜在的对象被垃圾回收
//	globalClazz = env->NewWeakGlobalRef(env, localClazz);
////	env->IsSameObject(env, ) // 检测弱全局变量是否 任然有效
////	if(JNI_FALSE)
////	if (JNI_OK == (env)->MonitorEnter(env, obj)) {
////
////	}
////
////	if (JNI_OK == (env->MonitorExit))
//
//	JavaVM* cachedJvm;
//	// 将当前的线程附着到虚拟机
//	(*cachedJvm)->AttachCurrentThread(cachedJvm, &env, NULL)
//	// 将当前的线程与虚拟机分离
////	(*cachedJvm)->DetachCurrentThread(cachedJvm);
//};
//
//
//
