/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_Native */

#ifndef _Included_com_example_jni_Native
#define _Included_com_example_jni_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_Native
 * Method:    add
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_Native_add__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_jni_Native
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_Native_add__II
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
