/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apress.swig;

public class Points {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Points(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Points obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UnixJNI.delete_Points(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Points() {
    this(UnixJNI.new_Points(), true);
  }

  public void funca(int a) {
    UnixJNI.Points_funca(swigCPtr, this, a);
  }

  public void fun(int a, int b) {
    UnixJNI.Points_fun(swigCPtr, this, a, b);
  }

}
