/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apress.swig;

public class UnixJNI {
  public final static native long new_Points();
  public final static native void delete_Points(long jarg1);
  public final static native void Points_funca(long jarg1, Points jarg1_, int jarg2);
  public final static native void Points_fun(long jarg1, Points jarg1_, int jarg2, int jarg3);
  public final static native int MAX_HEIGHT_get();
  public final static native long getuid() throws java.lang.IllegalAccessException;
}
